# Generated by Django 3.2.4 on 2021-09-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portal',
            name='time',
        ),
        migrations.AddField(
            model_name='portal',
            name='desigination',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='teacher', max_length=264),
        ),
    ]
